### ISSUE TITLE
possible to use url helpers within a presenter?

### ISSUE THREAD

**Issue by mguterl** [mhs/caching_presenter#1]
We're trying to extend our application's presenter to allow for something similar to this:

```
class JobPresenter < Board::Presenter
  def report_this_job_link
    link_to "Report this Job", flag_job_path(@job), :method => :post, :class => "action_button report"
  end
end
```

and

```
class MaskedJobPresenter < Board::Presenter
  def report_this_job_link
    nil
  end
end
```

We're trying to give access to the URL helpers by doing something like this:

```
class Board::Presenter < CachingPresenter
  include MaskableAttributes

  include ActionController::UrlWriter
  self.default_url_options = DefaultUrlOptions
end
```

First, this does not work:

```
undefined method `default_url_options' for #<Class:0x1015694e0>
/Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.01@rm-board/gems/activerecord-2.3.5/lib/active_record/base.rb:1959:in `method_missing_without_paginate'
/Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.01@rm-board/gems/will_paginate-2.3.12/lib/will_paginate/finder.rb:170:in `method_missing'
/Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.01@rm-board/gems/actionpack-2.3.5/lib/action_controller/url_rewriter.rb:127:in `url_for'
(eval):16:in `flag_job_path'
/Users/michaelguterl/code/rm/board/app/presenters/job_presenter.rb:6:in `_unmemoized_report_this_job_link'
/Users/michaelguterl/code/rm/board/app/views/jobs/show.html.erb:35:in `_run_erb_app47views47jobs47show46html46erb'
```

I'm curious if you can think of any reason why?  Could it have to do with the way caching is implemented?

Second, I'm not sure if this is even how presenters are meant to be used, I would love to hear your feedback on that.

**Comment by zdennis** [comment]
This is not currently available out of the box given the current implementation of CachingPresenter in combination with the current implementation of Rails.

CachingPresenter currently auto-delegates all methods to the object being presented on. When Rails tries to find the default_url_options it asks the current scope... "self.class.default_url_options". Because of this hard-coded reference to "self.class" CachingPresenter is unable to to provide the default_url_options itself. 

The "self.class" call ends up getting delegated to the object being presented on (usually the model).

You can get this to work for you in the same way you make routing helpers available to mailers or models by providing them with the default url options. For example:

```
class ActiveRecord::Base
  cattr_accessor :default_url_options
  self.default_url_options = {}
end
```

And then in your ApplicationController set up an around filter to set the default url options:

```
class ApplicationController
  around_filter do |controller, action|
    old_default_url_options = ActiveRecord::Base.default_url_options
    ActiveRecord::Base.default_url_options = { :host => controller.request.host, :port => controller.request.port }
    action.call
    ActiveRecord::Base.default_url_options = old_default_url_options
  end
end
```

You may want to massage the port so that if it's on port 80, then it omits it, otherwise Rails routing helpers will generates urls with a hard-coded port, ie: http://example.com:80/people

If you have any other questions let us know. Thanks!
